### PR TITLE
Update to .NET 7 and also nuget dependencies to current

### PR DESCRIPTION
**Pull request by xecrets**
Hi!

Here's a minimal but as far as I can tell, well working, upgrade of all projects to .NET 7, and all nuget packages to the latest current.

Much more can be done, but all warnings, including those related to the updates have been fixed, including some obsolete warnings.

I have not tried to build the Innosetup, but it should not really change anything. It is possible to build with .NET 7 a single executable, including embedded the whole .NET 7 code, trimming away all that's not needed etc in order to not require the consumer to have .NET 7 installed for example.

I don't really think it should be a problem to ask users to go to https://dotnet.microsoft.com/en-us/download/dotnet and download .NET 7, they'll be needing it anyway in many cases.

After releasing this, it should be fairly trivial to upgrade to .NET 8 when it's released as well.

### CODE REVIEW

**Comment by Sailfish** [comment]
Windows 7 and 8.1 only support up to Net 6.

 

From: Svante Seleborg ***@***.***> 
Sent: Tuesday, October 10, 2023 1:31 PM
To: audiamus/AaxAudioConverter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [audiamus/AaxAudioConverter] Update to .NET 7 and also nuget dependencies to current (PR #192)

 

Hi!

Here's a minimal but as far as I can tell, well working, upgrade of all projects to .NET 7, and all nuget packages to the latest current.

Much more can be done, but all warnings, including those related to the updates have been fixed, including some obsolete warnings.

I have not tried to build the Innosetup, but it should not really change anything. It is possible to build with .NET 7 a single executable, including embedded the whole .NET 7 code, trimming away all that's not needed etc in order to not require the consumer to have .NET 7 installed for example.

I don't really think it should be a problem to ask users to go to https://dotnet.microsoft.com/en-us/download/dotnet and download .NET 7, they'll be needing it anyway in many cases.

After releasing this, it should be fairly trivial to upgrade to .NET 8 when it's released as well.

  _____  


You can view, comment on, or merge this pull request online at:


  https://github.com/audiamus/AaxAudioConverter/pull/192


Commit Summary


*	44fdb9e <https://github.com/audiamus/AaxAudioConverter/pull/192/commits/44fdb9e23ed54d3da8dce91b6098586d844f8ef2>  Update to .NET 7 and also nuget dependencies to current


File Changes 


(26 <https://github.com/audiamus/AaxAudioConverter/pull/192/files>  files)

*	A .gitignore <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947>  (10) 
*	M src/AAX Audio Converter.sln <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-71bc8205ac1e1d4c2d9fca6ac1f368029741da5f6b251536975b9f855c9dd09b>  (20) 
*	M src/AaxAudioConverter/AaxAudioConverter.csproj <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-5e6b391e2501fb6a5a7c26caf900f1dc0b54b64124e98352724ba6ae2e848a9d>  (355) 
*	M src/AaxAudioConverter/App.config <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-a800d5d21b135cdac8487ad23fbee0806d1262b8b49e666723607dea2722e49f>  (206) 
*	M src/AaxAudioConverter/Program.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-da795b8cd20656263e00d8a359eb35543539db0b7ab1d2147d43d223304aa79d>  (1) 
*	M src/AaxAudioConverter/Properties/AssemblyInfo.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-83ca7f6cc6eb9ff1c1c8843b48432e6504527b574d2e578c9f1ad3d737e4ba93>  (3) 
*	M src/AaxAudioConverter/Properties/Settings.Designer.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-0c047e8c73fe8a8bb70c57f658a61d092793640a52d6a58b848885f4ee5de67a>  (2) 
*	M src/AaxAudioConverter/WhatsNewForm.resx <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-76c17a8bbd3f2e64bc3f39ebce2a6397d57e05902acd53e2ddf1d34aa40cc442>  (24) 
*	D src/AaxAudioConverter/packages.config <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-889921b38142de36f9332e5023b13979636af6e6b4aa4e6aee4918a4e1a98100>  (7) 
*	M src/AaxAudioConverterLib/AaxAudioConverterLib.csproj <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-09144db642255f16427967a8636cbaff250986423738966a292040e98613ec94>  (132) 
*	M src/AaxAudioConverterLib/CallbackWrapper.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-c6a50c9cd25f602d25f26002127815c9bfbd87c192404b2dc389d6c5bb3caa55>  (4) 
*	M src/AaxAudioConverterLib/Properties/AssemblyInfo.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-6b68b682d6e6cd5f8de48c9c689293c2ca18c86cbe7d5e8834b3a497eac75a5f>  (3) 
*	D src/AaxAudioConverterLib/packages.config <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-878cb3543bdb0b993a7722b6b664e9d0d16268a26e68efb38f22ce9e39354d9e>  (8) 
*	M src/AuxLib/ApplEnv.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-9e6bfe7559f250bd1d1b3f61175185fd1ad01b28c9018dbf65893bd48fadb542>  (2) 
*	M src/AuxLib/AuxLib.csproj <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-606ae12018bcfd16976e15d2b66a63a7f421c5ee46fad0ba294fcdc36ac3c04e>  (76) 
*	M src/AuxLib/Encoding.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-c30805c76131851e7a87fa3865a4aca3358d7d2d3852a2c661cae92b39af9418>  (2) 
*	M src/AuxWin32Lib/Properties/AssemblyInfo.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-a73b23de2e25bac1a2a523f8fdebb15a90931ed8250c8ef581281f37a9bdca2e>  (3) 
*	M src/AuxWin32Lib/auxWin32Lib.csproj <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-c066ec76ee5a2d6a3b37ae0be6d65ff7cd82db11e6ad74cb465f9f88fae0dc1c>  (49) 
*	M src/AuxWinLib/AuxWinLib.csproj <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-b7eab912109b489f19e1514d66b2420b664782e7fde3f37148a4a889b7eac0e4>  (75) 
*	M src/AuxWinLib/ControlExPathEllipsis.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-9152788baa5133cf9ef12255b4d55e15a3b938b80c0d373255140a511ad42fd7>  (55) 
*	M src/AuxWinLib/DialogBox/AuxWin.DialogBox.csproj <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-ff9dd23988f2bfc7c4f36541b2483ef4258e84cd96dc3972ccd68df61acf2df6>  (84) 
*	M src/AuxWinLib/Properties/AssemblyInfo.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-e09e7b66dae7f1f0ce3c60f5a70b4c847dfb0ea21f3d0c570ff800e16f5a8889>  (3) 
*	M src/PerfLib/PerfLib.csproj <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-55e055be956275642a662d359e791b6e2c2f506c53b6ccc2aa94a9a6f895c4a4>  (56) 
*	M src/PerfLib/Properties/AssemblyInfo.cs <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-df5ac0e407e21d2a2a118bdbeb160eee5404b8518c1fc4f0d5655ba97d58b20c>  (3) 
*	M src/PropGridLib/PropGridLib.csproj <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-107bfb14e480273eef23a5a6abf6c8ac8697dd0a88fc2547fb2ef7b5c15e2c14>  (54) 
*	M src/TreeDecomposition/TreeDecomposition.csproj <https://github.com/audiamus/AaxAudioConverter/pull/192/files#diff-f25c485409bbfc131d6ff925307dbbe1cd23a6c1a4cb9690efda64751cee4f49>  (60) 


Patch Links:


*	https://github.com/audiamus/AaxAudioConverter/pull/192.patch
*	https://github.com/audiamus/AaxAudioConverter/pull/192.diff

**Comment by xecrets** [comment]
> Windows 7 and 8.1 only support up to Net 6. 

Windows 7 and 8.1 are not supported at all. They both reached end of extended support January 10, 2023, and should not be used or encouraged to be used.

Whether .NET 6 technically will continue to run on these platforms I don't know, but also there, the official standpoint is that the lifecycle of .NET is the same as the underlying operating system, i.e. .NET 6 is not supported on Windows 7 and 8.1 . See https://github.com/dotnet/core/issues/7556 .

If @audiamus will consider an upgrade to .NET 6 instead it should not be difficult to "downgrade" this pull request. The big hurdle is from .NET Framework to .NET 5+. And upgrading to .NET 6 is better than staying with .NET Framework 4.8 in any case, for example the dependency to z440.atl.com requires an upgrade to .NET for version 5+, see https://www.nuget.org/packages/z440.atl.core#supportedframeworks-body-tab .

**Comment by Sailfish** [comment]
Hello Svante, I will defer to audiamus for his position regarding .NET 6 and .NET 7 support on Windows 7; however, it is my understanding that AaxAudioConverter has already been updated to .NET6 support.

**Comment by xecrets** [comment]
> ... it is my understanding that AaxAudioConverter has already been updated to .NET6 support.
Not in the one and only master branch published on github - but there are some indications that maybe the gihub repo is not the primary location of the source code, but rather a publishing channel, so it could have been done elsewhere already.

**Comment by Sailfish** [comment]
Ref: discussion [#170]

It appears that only BookLibConnect is based on .NET 6 with AaxAudioConverter 2 being slated for .NET 6 or .NET 7.

**Comment by audiamus** [comment]
There are a number of reasons why I have not yet migrated AAXAudioConverter to .Net Core (5,6,7...). 

The plan is to merge [BookLibConnect](https://github.com/audiamus/BookLibConnect) into AaxAudioConverter and hereby doing some redesign, e.g.:

- Those external FFmpeg processes will be replaced with the in-process library [AAXClean](https://github.com/Mbucari/AAXClean) by @Mbucari, already in use in BookLibConnect.
- The WinForms mechanism for xml app and user settings will be replaced with an easier to maintain home-made json solution, also already in use in BookLibConnect.
- The WinForms ListView control will be replaced with a DataGridView, that allows much better customization, also to be found in BookLibConnect. 
- Couple of other changes.

BookLibConnect was written for .Net 5 and later updated to .Net 6. For this, a number of libraries in AaxAudioConverter have already been ported, identifiable by _core_ as namespace prefix or assembly suffix. (_I have been working with .Net Core since version 2 in my pro job and always kept the _Core_ name to distinguish the code from classic .Net Framework._) There are also a few pitfalls when migrating from Framework to Core, not obvious at first glance, and not triggering compiler errors or warnings.

I will probably skip .Net 7 altogether, because of its relatively short lifecycle. We have to see about Win 7. It may indeed happen that Win 7 can no longer be supported once my tools run with .Net 8. 

Only "big problem" is that I don't seem to find the time to tackle this in earnest, but it will happen. Therefore please understand that I won't want an intermediate "update" to .Net 7.

**Comment by xecrets** [comment]
> The plan is to merge [BookLibConnect](https://github.com/audiamus/BookLibConnect) into AaxAudioConverter and hereby doing some redesign, e.g.:
> ...

Sounds nice!

> There are also a few pitfalls when migrating from Framework to Core, not obvious at first glance, and not triggering compiler errors or warnings.

Understood, for what it's worth, the PR does seem to work - but I have not tested extensively.

> I will probably skip .Net 7 altogether, because of its relatively short lifecycle. We have to see about Win 7. It may indeed happen that Win 7 can no longer be supported once my tools run with .Net 8.

Yes, doing .NET 7 now is just a precursor to the LTS release of .NET 8. But it makes no sense really to go for .NET 6 either, the lifetime is almost the same as .NET 7.

> Only "big problem" is that I don't seem to find the time to tackle this in earnest, but it will happen. Therefore please understand that I won't want an intermediate "update" to .Net 7.

Ok, understood. Hopefully you might find some useful stuff there anyway, some fixes to warnings such as comparing a struct with null and a fix to obsoleted dangerous use of rewriting strings with `TextFormatFlags.ModifyString` .

I did not spend much time on this anyway, and the only reason was I wanted to ensure use of the latest ATL library in relation to issue #193 , as I wanted to rule out that the issue was there and wanted to be able to build and use the latest & greatest there. Then, when I had done it, I thought I might as well at least offer it to you! So I won't be very disappointed if you throw it out ;-) .

If you'd like some help, do contact me directly and perhaps I could be of some assistance and I may have some spare time.

As a side note, it seems you're not really using github as your main development repository, but if you're interested in getting help with contributions, it facilitates if the development process is more transparent directly on github. I find this way of working is very good for my personal projects.

**Comment by audiamus** [comment]
> As a side note, it seems you're not really using github as your main development repository

That's correct. I prefer to develop independently of any web server. And my repo is SVN, not Git. I only export to Git once for each release.

**Comment by xecrets** [comment]
> > As a side note, it seems you're not really using github as your main development repository
> 
> That's correct. I prefer to develop independently of any web server. And my repo is SVN, not Git. I only export to Git once for each release.

😉 Figured as much. There's some traces of Subversion in one of the project files... Your choice! But... I was once a Subversion fan, then TFS, then Mercurial - but although Mercurial really is better in many ways than Git, in the end it's not always what's best that wins the battle. Remember VHS vs. Betamax! So I gave up fighting city hall, and now only use Git. It works, quite well actually, and much better than Subversion and TFS anyway. Oh well, everybody to their own!

**Pull request closed without merging**
